# 是否显示进度
print-progress: true

# 并发线程数
concurrent: 20

# 检查间隔(分钟)
check-interval: 30

# 超时时间(毫秒)(节点的最大延迟)
timeout: 5000

# 测速地址
speed-test-url: https://gh-proxy.henryjiu.workers.dev/https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z

# 最低测速结果舍弃(KB/s)
min-speed: 1024

# 下载测试时间(s)
download-timeout: 10

# 监听端口（GitHub Actions 不需要端口，可忽略）
listen-port: ":8199"

# 以节点IP查询位置重命名节点
rename-node: false

# 保留之前测试成功的节点
keep-success-proxies: false

# 输出目录（适配 GitHub Actions）
output-dir: "./output"

# Telegram 通知（直接使用 API，由工作流处理）
recipient-url:
  - "telegram://placeholder"  # 占位符，实际由工作流注入

# 保存方法
save-method: gist

# Gist 配置
github-gist-id: "${{ secrets.GIST_ID }}"  # 从 Secrets 获取
github-token: "${{ secrets.GITHUB_TOKEN }}"  # 从 Secrets 获取
github-api-mirror: "https://2.ikunya.ggff.net/github"

# 订阅地址（从 url.txt 读取，由工作流动态替换）
sub-urls:
  - "placeholder"
